all: make_redis make_couchdb make_mysql make_postgres make_memcached make_rabbitmq

make_couchdb:
	make -C ./couchdb

make_mongodb:
	make -C ./mongodb

make_mysql:
	make -C ./mysql

make_postgres:
	make -C ./postgres

make_redis:
	make -C ./redis

make_rabbitmq:
	make -C ./rabbitmq

make_memcached:
	make -C ./memcached


